#BedwarsKit配置文件

#是否启用挖床标题
break_bed_title: true
#可用变量:
#{BreakPlayerName} = 破坏床的玩家的名字
#{BreakPlayerTeamColor} = 破坏床的玩家的队伍颜色代码
#{breakPlayerTeamName} = 破坏床的玩家的队伍名字
#{BreakTeamName} 被破坏床的玩家的队伍名字
#{BreakTeamColor} = 被破坏床的玩家的队伍颜色代码
break_title_all: "{BreakTeamColor}{BreakTeamName}&c的床已被摧毁"
break_subtitle_all: "&7摧毁者:{BreakPlayerTeamColor}{BreakPlayerName}"
break_title_breakPlayer: "{BreakTeamColor}{BreakTeamName}"
break_subtitle_breakPlayer: "&a床已被你摧毁"
break_title_breakTeam: "&c床已被摧毁"
break_subtitle_breakTeam: "&7摧毁者:{BreakPlayerTeamColor}{BreakPlayerName}"

#是否禁用饥饿值
no_hunger: true

#是否禁用末影珍珠伤害
#这将同时禁用摔落伤害
no_pearl_damage: true

#防卡床
#在玩家破坏床时检查脚下时候为床
#向上传送,以防止卡在床内
break_bed_check: true
#设置为传送时向上传送的距离,必须是double类型,比如-2.0, 5.28
tp_dis: 0.74

#自定义计分板
#使用自定义的计分板
custom_scoreboard: true
scoreboard_title: "&e起床战争"

#死亡游戏模式
#修复了一个细节，因为Bedwars1058在复活倒计时时玩家人物不会隐身
#这将将玩家的游戏模式设置为旁观模式
death_gamemode: true
#重生中标题与副标题
#变量:
#{timeleft} = 剩余时间
respawn_title: "&e{timeleft}&a秒后复活"
respawn_subtitle: ""
#已重生标题与副标题
#变量:
#{timeleft} = 剩余时间
respawn_succ_title: "&a已回城"
respawn_succ_subtitle: ""

meaning_teambed_yes: "&a&l✔"
meaning_team_none: "&c&l✘"
#变量
#{aliveCount} = 存活人数
meaning_teambed_no: "&f{aliveCount}"
#变量
#{teamColor} = 队伍颜色
meaning_You: "{teamColor}➜"
meaning_NotYou: "  "

#判断为疾速模式的依据
rushworld: "rush"

#保留信息
#ArmorLevel
#0:Leather
#1:ChainMail
#2:Iron
#3:Diamond